Removed support for type string from `is`
Download/mics pull request #35
Opened 2017-07-13 15:39 UTC by Download

Fixes #22 

@minecrawler  Can you let me know what you think?

(I changed one ESLint setting... Just got rid of some blank lines.. Hope you can live with it?)

2017-07-13 16:03 UTC, minecrawler commented
As for the linting: If that's what you want, I can't stop you. I am only concerned with readability for other developers here.

Other than that: Could you try to separate changes you do into several commit in the future? It keeps the history expressive and documentary.

2017-07-13 16:03 UTC, minecrawler requested changes

2017-07-13 16:03 UTC, minecrawler commented on src/index.js
> +        || /^.*classCallCheck\(/.test(s.replace(/^[^{]*{\s*/,'').replace(/\s*}[^}]*$/,'')))(x.toString())
What purpose does that arrow function serve? Why not assign `const s = x.toString()` and execute that stuff directly in the scope of `isClass()`?

Also, imho, creating such a long expression is hard to read. If this is about saving bytes, then leave it to Babel :) Keep the source clean and easy to read and let the transpiler do the dirty work!

2017-07-13 21:11 UTC, Download commented on src/index.js
> +        || /^.*classCallCheck\(/.test(s.replace(/^[^{]*{\s*/,'').replace(/\s*}[^}]*$/,'')))(x.toString())
Ok but that is a different issue. This was about removing the type strings (`'class'`, `'factory'` etc) support from `is()` and `like()`.

2017-07-13 21:12 UTC, Download commented on src/index.js
> +        || /^.*classCallCheck\(/.test(s.replace(/^[^{]*{\s*/,'').replace(/\s*}[^}]*$/,'')))(x.toString())
Do you want me to change this for this PR?

2017-07-13 21:16 UTC, Download commented
> As for the linting: If that's what you want, I can't stop you.

Mmm... That's not good.

I was hoping you got the feeling that, yes, you can stop me.
We are in this together.

I sincerely feel the extra whitespace reduces readability... Maybe it's because I have a widescreen monitor that is not FullHD... so I don't have so much vertical space... too much scrolling.

But my monitor should not dictate style guides. So please let me know and I can change it back if it bothers you.

2017-07-14 08:39 UTC, minecrawler commented on src/index.js
> +        || /^.*classCallCheck\(/.test(s.replace(/^[^{]*{\s*/,'').replace(/\s*}[^}]*$/,'')))(x.toString())
> Ok but that is a different issue.

it's new code in this PR, so it is directly related ;)

> Do you want me to change this

yeah. If you cannot give a decent explanation, just [KISS](https://en.wikipedia.org/wiki/KISS_principle).

2017-07-14 08:58 UTC, minecrawler commented
> widescreen monitor that is not FullHD

oh, I see how your style developed (it's probably comparable to my laptop screen, which I cannot work with)! Sitting here with my two FullHD 16:9 monitors, of which one is rotated by 90° in order to see more code. For me ([and many other devs](https://hashnode.com/post/how-many-monitors-do-you-guys-use-to-codedesignwork-ciwvsi52q00u08k53bcujxx6x)), having many big monitors is quite natural. Your and my world are hard to compare, I guess.

Though because of above reasons, usually "clean code" is code which unfolds vertically, adding logical blocks (like grouping variable declarations) and full code constructs (like `if() {}` over at least three lines) instead of shortcuts (like `c = a && b`). Writing very stable, distinct code is what should be the driver (hence the preference for `;`). To sum it up, code which would force you to type and scroll a lot.

Imho, while general coding standards are a good thing, I can't have you as the project owner and main developer get unmotivated, because the project becomes tedious for you. So, while I still think that some changes to a few of the overly-long statements should be considered, let's try to keep vertical white spaces 
 and vertically unfolded expressions to a minimum for now.

On that note, maybe I can also introduce you to [Hashnode](https://hashnode.com/), which is a very nice and welcoming developer community to discuss tech and techniques, guidelines and practices. People also share many useful links about the latest developments, so you stay up2date as a plus. If you are interested, I would be delighted to see you around :)

2017-07-14 13:05 UTC, Download commented on src/index.js
> +        || /^.*classCallCheck\(/.test(s.replace(/^[^{]*{\s*/,'').replace(/\s*}[^}]*$/,'')))(x.toString())
I will change it.  

The explanation is that it's a trick to avoid having to declare a new variable. It just saves some bytes.

2017-07-14 13:21 UTC, minecrawler commented on src/index.js
> +        || /^.*classCallCheck\(/.test(s.replace(/^[^{]*{\s*/,'').replace(/\s*}[^}]*$/,'')))(x.toString())
> It just saves some bytes.

KISS, make sure it is readable. The rest should be handled by the transpiler. Also `const s =` vs `=>()` is safing two bytes at the expense of performance (the interpreter has to allocate a new closure) and readability. I feel that our internet today is fast enough to handle those two bytes ;)

2017-07-14 13:30 UTC, Download commented
Hashnode looks interesting! Thanks for the tip.

2017-07-14 13:38 UTC, minecrawler approved these changes
LGTM

2017-07-14 13:56 UTC, merged